POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "kannana1",
    "name": "Anirudh Kannan",
    "password": "secret"
}





// created users

# {
#     "username": "kannana1",
#     "name": "Anirudh Kannan",
#     "password": "secret"
# }
