POST http://localhost:3003/api/blogs/60f76b2782f841bc094ee0c9/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imthbm5hbmExIiwiaWQiOiI2MGU1MWYwZjRkNTVjNjcwODJiYmI0YWMiLCJpYXQiOjE2MjY4MjYzNTl9.z9JaDLZ9uLjJhmyqBrCUzkzAx0kVIEWya8TrJhxgPpM

{
    "comment": "The first comment after (apparently) fully implementing backend"
}

